//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int As_Id { get; set; }
        public string As_Name { get; set; }
        public string As_FileName { get; set; }
        public string As_Type { get; set; }
        public System.DateTime As_CrtTime { get; set; }
        public int As_Size { get; set; }
        public string As_Uid { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int As_Width { get; set; }
        public int As_Height { get; set; }
        public string As_Extension { get; set; }
        public int As_Duration { get; set; }
        public bool As_IsOuter { get; set; }
        public bool As_IsOther { get; set; }
    }
}
