//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Ac_ID { get; set; }
        public Nullable<int> Ac_PID { get; set; }
        public string Ac_AccName { get; set; }
        public string Ac_Pw { get; set; }
        public string Ac_Name { get; set; }
        public string Ac_Pinyin { get; set; }
        public string Ac_IDCardNumber { get; set; }
        public string Ac_Signature { get; set; }
        public Nullable<int> Ac_Age { get; set; }
        public Nullable<int> Ac_Sex { get; set; }
        public string Ac_Photo { get; set; }
        public Nullable<decimal> Ac_Money { get; set; }
        public Nullable<int> Ac_Point { get; set; }
        public Nullable<int> Ac_Coupon { get; set; }
        public Nullable<System.DateTime> Ac_Birthday { get; set; }
        public Nullable<bool> Ac_IsUse { get; set; }
        public Nullable<bool> Ac_IsPass { get; set; }
        public Nullable<bool> Ac_IsTeacher { get; set; }
        public string Ac_Qus { get; set; }
        public string Ac_Ans { get; set; }
        public Nullable<System.DateTime> Ac_RegTime { get; set; }
        public Nullable<System.DateTime> Ac_OutTime { get; set; }
        public Nullable<System.DateTime> Ac_LastTime { get; set; }
        public string Ac_LastIP { get; set; }
        public string Ac_Tel { get; set; }
        public Nullable<bool> Ac_IsOpenTel { get; set; }
        public string Ac_MobiTel1 { get; set; }
        public string Ac_MobiTel2 { get; set; }
        public Nullable<bool> Ac_IsOpenMobile { get; set; }
        public string Ac_Email { get; set; }
        public string Ac_Qq { get; set; }
        public string Ac_Weixin { get; set; }
        public string Ac_CheckUID { get; set; }
        public string Ac_UID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public string Ac_Zip { get; set; }
        public string Ac_LinkMan { get; set; }
        public string Ac_LinkManPhone { get; set; }
        public string Ac_Intro { get; set; }
        public string Ac_Major { get; set; }
        public string Ac_Education { get; set; }
        public string Ac_Native { get; set; }
        public string Ac_Nation { get; set; }
        public string Ac_CodeNumber { get; set; }
        public string Ac_Address { get; set; }
        public string Ac_AddrContact { get; set; }
        public Nullable<int> Dep_Id { get; set; }
        public Nullable<int> Sts_ID { get; set; }
        public string Sts_Name { get; set; }
        public Nullable<int> Ac_CurrCourse { get; set; }
        public Nullable<int> Ac_PointAmount { get; set; }
        public string Ac_School { get; set; }
        public string Ac_QqOpenID { get; set; }
        public string Ac_WeixinOpenID { get; set; }
    }
}
