//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressList
    {
        public int Adl_Id { get; set; }
        public int Ads_Id { get; set; }
        public string Ads_Name { get; set; }
        public string Adl_Name { get; set; }
        public int Adl_Sex { get; set; }
        public string Adl_Type { get; set; }
        public string Adl_Tel { get; set; }
        public string Adl_CoTel { get; set; }
        public string Adl_MobileTel { get; set; }
        public string Adl_Email { get; set; }
        public string Adl_QQ { get; set; }
        public string Adl_Msn { get; set; }
        public string Adl_Blog { get; set; }
        public string Adl_Company { get; set; }
        public string Adl_Address { get; set; }
        public string Adl_Zip { get; set; }
        public System.DateTime Adl_Birthday { get; set; }
        public string Adl_Like { get; set; }
        public string Adl_Intro { get; set; }
        public int Acc_Id { get; set; }
        public string Adl_Post { get; set; }
        public string Adl_Political { get; set; }
        public int Adl_State { get; set; }
        public System.DateTime Adl_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
