//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Art_Id { get; set; }
        public string Col_Name { get; set; }
        public int Col_Id { get; set; }
        public string Art_Title { get; set; }
        public string Art_TitleAbbr { get; set; }
        public string Art_TitleFull { get; set; }
        public string Art_TitleSub { get; set; }
        public string Art_Color { get; set; }
        public string Art_Font { get; set; }
        public bool Art_IsError { get; set; }
        public string Art_ErrInfo { get; set; }
        public bool Art_IsUse { get; set; }
        public bool Art_IsShow { get; set; }
        public bool Art_IsImg { get; set; }
        public bool Art_IsHot { get; set; }
        public bool Art_IsTop { get; set; }
        public bool Art_IsRec { get; set; }
        public bool Art_IsDel { get; set; }
        public bool Art_IsVerify { get; set; }
        public string Art_VerifyMan { get; set; }
        public bool Art_IsOut { get; set; }
        public string Art_OutUrl { get; set; }
        public string Art_Keywords { get; set; }
        public string Art_Descr { get; set; }
        public string Art_Author { get; set; }
        public int Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public string Art_Source { get; set; }
        public string Art_Intro { get; set; }
        public string Art_Details { get; set; }
        public string Art_Endnote { get; set; }
        public System.DateTime Art_CrtTime { get; set; }
        public System.DateTime Art_LastTime { get; set; }
        public System.DateTime Art_VerifyTime { get; set; }
        public int Art_Number { get; set; }
        public bool Art_IsNote { get; set; }
        public string Art_Logo { get; set; }
        public bool Art_IsStatic { get; set; }
        public System.DateTime Art_PushTime { get; set; }
        public string Art_Label { get; set; }
        public string Art_Uid { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
