//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Columns
    {
        public int Col_ID { get; set; }
        public int Col_PID { get; set; }
        public string Col_Name { get; set; }
        public string Col_ByName { get; set; }
        public string Col_Title { get; set; }
        public string Col_Keywords { get; set; }
        public string Col_Descr { get; set; }
        public string Col_Intro { get; set; }
        public string Col_Type { get; set; }
        public int Col_Tax { get; set; }
        public bool Col_IsUse { get; set; }
        public bool Col_IsNote { get; set; }
        public System.DateTime Col_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
