//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponAccount
    {
        public int Ca_ID { get; set; }
        public int Ac_ID { get; set; }
        public int Ca_Total { get; set; }
        public int Ca_TotalAmount { get; set; }
        public int Ca_Value { get; set; }
        public string Ca_Source { get; set; }
        public int Ca_Type { get; set; }
        public string Ca_Info { get; set; }
        public string Ca_Remark { get; set; }
        public System.DateTime Ca_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Ca_Serial { get; set; }
        public int Ca_From { get; set; }
        public string Rc_Code { get; set; }
    }
}
