//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Cou_ID { get; set; }
        public string Cou_Name { get; set; }
        public string Cou_Logo { get; set; }
        public string Cou_LogoSmall { get; set; }
        public int Cou_Tax { get; set; }
        public string Cou_Intro { get; set; }
        public string Cou_Target { get; set; }
        public string Cou_Content { get; set; }
        public bool Cou_IsUse { get; set; }
        public bool Cou_IsFree { get; set; }
        public bool Cou_IsStudy { get; set; }
        public int Cou_StudentSum { get; set; }
        public int Cou_Price { get; set; }
        public System.DateTime Cou_CrtTime { get; set; }
        public int Cou_Score { get; set; }
        public int Cou_ViewNum { get; set; }
        public int Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
        public int Cou_PID { get; set; }
        public int Cou_Level { get; set; }
        public string Cou_XPath { get; set; }
        public string Cou_UID { get; set; }
        public bool Cou_IsTry { get; set; }
        public int Cou_TryNum { get; set; }
        public int Dep_Id { get; set; }
        public string Dep_CnName { get; set; }
        public bool Cou_IsRec { get; set; }
        public string Cou_PriceUnit { get; set; }
        public int Cou_PriceSpan { get; set; }
        public bool Cou_IsLimitFree { get; set; }
        public System.DateTime Cou_FreeStart { get; set; }
        public System.DateTime Cou_FreeEnd { get; set; }
        public bool Cou_ExistLive { get; set; }
        public bool Cou_ExistQues { get; set; }
        public bool Cou_ExistExam { get; set; }
    }
}
