//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePrice
    {
        public int CP_ID { get; set; }
        public int CP_Tax { get; set; }
        public int CP_Price { get; set; }
        public int CP_Span { get; set; }
        public string CP_Unit { get; set; }
        public bool CP_IsUse { get; set; }
        public string CP_Group { get; set; }
        public int Cou_ID { get; set; }
        public string Cou_UID { get; set; }
        public int Org_ID { get; set; }
        public int CP_Coupon { get; set; }
    }
}
