//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depart
    {
        public int Dep_Id { get; set; }
        public string Dep_CnName { get; set; }
        public string Dep_Code { get; set; }
        public int Dep_Tax { get; set; }
        public bool Dep_IsUse { get; set; }
        public bool Dep_IsShow { get; set; }
        public bool Dep_IsAdmin { get; set; }
        public int Dep_PatId { get; set; }
        public int Dep_Level { get; set; }
        public string Dep_Func { get; set; }
        public string Dep_Phone { get; set; }
        public string Dep_Msn { get; set; }
        public string Dep_Fax { get; set; }
        public string Dep_Email { get; set; }
        public string Dep_WorkAddr { get; set; }
        public string Dep_CnAbbr { get; set; }
        public string Dep_EnAbbr { get; set; }
        public string Dep_EnName { get; set; }
        public bool Dep_State { get; set; }
        public int Dep_Count { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
