//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAccount
    {
        public int Acc_Id { get; set; }
        public string Acc_AccName { get; set; }
        public string Acc_Pw { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_NamePinyin { get; set; }
        public string Acc_IDCardNumber { get; set; }
        public string Acc_Signature { get; set; }
        public int Acc_Sex { get; set; }
        public int Acc_Age { get; set; }
        public System.DateTime Acc_Birthday { get; set; }
        public bool Acc_IsUse { get; set; }
        public string Acc_Email { get; set; }
        public string Acc_Qus { get; set; }
        public string Acc_Ans { get; set; }
        public string Acc_EmpCode { get; set; }
        public System.DateTime Acc_RegTime { get; set; }
        public System.DateTime Acc_OutTime { get; set; }
        public bool Acc_IsAutoOut { get; set; }
        public System.DateTime Acc_LastTime { get; set; }
        public string Acc_Tel { get; set; }
        public bool Acc_IsOpenTel { get; set; }
        public string Acc_MobileTel { get; set; }
        public bool Acc_IsOpenMobile { get; set; }
        public string Acc_QQ { get; set; }
        public int Dep_Id { get; set; }
        public string Dep_CnName { get; set; }
        public int Posi_Id { get; set; }
        public string Posi_Name { get; set; }
        public int EGrp_Id { get; set; }
        public string Acc_Photo { get; set; }
        public bool Acc_IsUseCard { get; set; }
        public string Acc_Weixin { get; set; }
        public int Title_Id { get; set; }
        public string Title_Name { get; set; }
        public bool Acc_IsPartTime { get; set; }
        public int Team_ID { get; set; }
        public string Team_Name { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
