//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamGroup
    {
        public int Eg_ID { get; set; }
        public Nullable<int> Eg_Type { get; set; }
        public int Sts_ID { get; set; }
        public string Exam_UID { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
