//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResultsTemp
    {
        public int Exr_ID { get; set; }
        public Nullable<float> Exr_Score { get; set; }
        public string Exr_Results { get; set; }
        public Nullable<System.DateTime> Exr_CrtTime { get; set; }
        public string Exr_IP { get; set; }
        public string Exr_Mac { get; set; }
        public bool Exr_IsSubmit { get; set; }
        public Nullable<int> Exam_ID { get; set; }
        public Nullable<int> Sbj_ID { get; set; }
        public Nullable<int> Tp_Id { get; set; }
        public Nullable<int> Acc_Id { get; set; }
    }
}
