//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int Exam_ID { get; set; }
        public string Exam_Title { get; set; }
        public System.DateTime Exam_CrtTime { get; set; }
        public string Exam_Intro { get; set; }
        public bool Exam_IsUse { get; set; }
        public bool Exam_IsTheme { get; set; }
        public int Exam_GroupType { get; set; }
        public string Exam_Monitor { get; set; }
        public System.DateTime Exam_Date { get; set; }
        public int Exam_Span { get; set; }
        public int Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public string Exam_UID { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
        public int Tp_Id { get; set; }
        public int Exam_PassScore { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public string Exam_Name { get; set; }
        public int Exam_Total { get; set; }
        public int Exam_Tax { get; set; }
        public System.DateTime Exam_DateOver { get; set; }
        public int Exam_DateType { get; set; }
        public bool Exam_IsToggle { get; set; }
        public bool Exam_IsShowBtn { get; set; }
        public bool Exam_IsRightClick { get; set; }
    }
}
