//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int Fm_ID { get; set; }
        public string Fm_Title { get; set; }
        public bool Fm_IsTheme { get; set; }
        public string Fm_Content { get; set; }
        public int Fm_PID { get; set; }
        public string Fm_UID { get; set; }
        public int Fm_At { get; set; }
        public System.DateTime Fm_CrtTime { get; set; }
        public Nullable<System.DateTime> Fm_LastTime { get; set; }
        public string Fm_IP { get; set; }
        public int Fm_ViewNumber { get; set; }
        public int Fm_ReplyNumber { get; set; }
        public bool Fm_IsDel { get; set; }
        public bool Fm_IsTop { get; set; }
        public bool Fm_IsRec { get; set; }
        public Nullable<int> Ac_ID { get; set; }
        public string Ac_Name { get; set; }
        public Nullable<int> Th_ID { get; set; }
        public string Th_Name { get; set; }
        public Nullable<int> Org_ID { get; set; }
    }
}
