//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideColumns
    {
        public int Gc_ID { get; set; }
        public int Gc_PID { get; set; }
        public int Cou_ID { get; set; }
        public string Cou_Name { get; set; }
        public string Gc_ByName { get; set; }
        public string Gc_Title { get; set; }
        public string Gc_Keywords { get; set; }
        public string Gc_Descr { get; set; }
        public string Gc_Intro { get; set; }
        public string Gc_Type { get; set; }
        public int Gc_Tax { get; set; }
        public bool Gc_IsUse { get; set; }
        public bool Gc_IsNote { get; set; }
        public System.DateTime Gc_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
