//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knowledge
    {
        public int Kn_ID { get; set; }
        public string Kns_Name { get; set; }
        public Nullable<int> Kns_ID { get; set; }
        public string Kn_Title { get; set; }
        public string Kn_TitleFull { get; set; }
        public string Kn_TitleSub { get; set; }
        public bool Kn_IsUse { get; set; }
        public bool Kn_IsTop { get; set; }
        public bool Kn_IsRec { get; set; }
        public bool Kn_IsHot { get; set; }
        public bool Kn_IsDel { get; set; }
        public string Kn_Keywords { get; set; }
        public string Kn_Descr { get; set; }
        public string Kn_Author { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
        public string Kn_Source { get; set; }
        public string Kn_Intro { get; set; }
        public string Kn_Details { get; set; }
        public Nullable<System.DateTime> Kn_CrtTime { get; set; }
        public Nullable<System.DateTime> Kn_LastTime { get; set; }
        public int Kn_Number { get; set; }
        public bool Kn_IsNote { get; set; }
        public string Kn_Logo { get; set; }
        public string Kn_Label { get; set; }
        public string Kn_Uid { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Cou_ID { get; set; }
    }
}
