//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeSort
    {
        public int Kns_ID { get; set; }
        public string Kns_Name { get; set; }
        public string Kns_ByName { get; set; }
        public int Kns_PID { get; set; }
        public int Kns_Tax { get; set; }
        public bool Kns_IsUse { get; set; }
        public string Kns_Type { get; set; }
        public string Kns_Intro { get; set; }
        public Nullable<System.DateTime> Kns_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Cou_ID { get; set; }
    }
}
