//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningCard
    {
        public int Lc_ID { get; set; }
        public string Lc_Code { get; set; }
        public string Lc_Pw { get; set; }
        public float Lc_Price { get; set; }
        public int Lc_Coupon { get; set; }
        public System.DateTime Lc_CrtTime { get; set; }
        public System.DateTime Lc_UsedTime { get; set; }
        public bool Lc_IsEnable { get; set; }
        public bool Lc_IsUsed { get; set; }
        public int Lcs_ID { get; set; }
        public int Ac_ID { get; set; }
        public string Ac_AccName { get; set; }
        public int Org_ID { get; set; }
        public System.DateTime Lc_LimitStart { get; set; }
        public System.DateTime Lc_LimitEnd { get; set; }
        public int Lc_State { get; set; }
        public string Lc_QrcodeBase64 { get; set; }
        public int Lc_Span { get; set; }
    }
}
