//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningCardSet
    {
        public int Lcs_ID { get; set; }
        public string Lcs_RelatedCourses { get; set; }
        public int Lcs_CoursesCount { get; set; }
        public int Lcs_Count { get; set; }
        public int Lcs_MaxCount { get; set; }
        public int Lcs_BuildCount { get; set; }
        public bool Lcs_IsFixed { get; set; }
        public float Lcs_Price { get; set; }
        public int Lcs_Coupon { get; set; }
        public int Lcs_Span { get; set; }
        public string Lcs_Unit { get; set; }
        public System.DateTime Lcs_CrtTime { get; set; }
        public string Lcs_Theme { get; set; }
        public string Lcs_Intro { get; set; }
        public int Lsc_UsedCount { get; set; }
        public int Org_ID { get; set; }
        public System.DateTime Lcs_LimitStart { get; set; }
        public System.DateTime Lcs_LimitEnd { get; set; }
        public bool Lcs_IsEnable { get; set; }
        public int Lcs_CodeLength { get; set; }
        public int Lcs_PwLength { get; set; }
        public string Lcs_SecretKey { get; set; }
    }
}
