//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int Lk_Id { get; set; }
        public Nullable<int> Ls_Id { get; set; }
        public string Ls_Name { get; set; }
        public string Lk_Name { get; set; }
        public string Lk_Url { get; set; }
        public Nullable<int> Lk_Tax { get; set; }
        public bool Lk_IsUse { get; set; }
        public string Lk_Logo { get; set; }
        public string Lk_LogoSmall { get; set; }
        public bool Lk_IsShow { get; set; }
        public string Lk_Tootip { get; set; }
        public string Lk_Email { get; set; }
        public bool Lk_IsApply { get; set; }
        public bool Lk_IsVerify { get; set; }
        public string Lk_SiteMaster { get; set; }
        public string Lk_QQ { get; set; }
        public string Lk_Mobile { get; set; }
        public string Lk_Explain { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
