//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinksSort
    {
        public int Ls_Id { get; set; }
        public Nullable<int> Ls_PatId { get; set; }
        public string Ls_Name { get; set; }
        public Nullable<int> Ls_Tax { get; set; }
        public bool Ls_IsUse { get; set; }
        public string Ls_Logo { get; set; }
        public bool Ls_IsShow { get; set; }
        public string Ls_Tootip { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public bool Ls_IsImg { get; set; }
        public bool Ls_IsText { get; set; }
    }
}
