//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogForStudentQuestions
    {
        public int Lsq_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Ac_ID { get; set; }
        public string Ac_AccName { get; set; }
        public Nullable<int> Cou_ID { get; set; }
        public Nullable<int> Ol_ID { get; set; }
        public Nullable<System.DateTime> Lsq_CrtTime { get; set; }
        public Nullable<System.DateTime> Lsq_LastTime { get; set; }
        public Nullable<int> Qus_ID { get; set; }
        public Nullable<int> Lsq_Index { get; set; }
    }
}
