//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogForStudentStudy
    {
        public int Lss_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Ac_ID { get; set; }
        public string Ac_AccName { get; set; }
        public string Ac_Name { get; set; }
        public Nullable<int> Cou_ID { get; set; }
        public Nullable<int> Ol_ID { get; set; }
        public string Lss_UID { get; set; }
        public Nullable<System.DateTime> Lss_CrtTime { get; set; }
        public Nullable<int> Lss_PlayTime { get; set; }
        public Nullable<int> Lss_StudyTime { get; set; }
        public Nullable<int> Lss_Duration { get; set; }
        public Nullable<System.DateTime> Lss_LastTime { get; set; }
        public string Lss_IP { get; set; }
        public string Lss_Browser { get; set; }
        public string Lss_Platform { get; set; }
        public string Lss_OS { get; set; }
    }
}
