//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogForStudentOnline
    {
        public int Lso_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Ac_ID { get; set; }
        public string Ac_AccName { get; set; }
        public string Ac_Name { get; set; }
        public string Lso_UID { get; set; }
        public Nullable<System.DateTime> Lso_LoginDate { get; set; }
        public Nullable<System.DateTime> Lso_LoginTime { get; set; }
        public Nullable<System.DateTime> Lso_LastTime { get; set; }
        public Nullable<System.DateTime> Lso_LogoutTime { get; set; }
        public Nullable<System.DateTime> Lso_CrtTime { get; set; }
        public Nullable<int> Lso_OnlineTime { get; set; }
        public Nullable<int> Lso_BrowseTime { get; set; }
        public string Lso_IP { get; set; }
        public string Lso_Browser { get; set; }
        public string Lso_Platform { get; set; }
        public string Lso_OS { get; set; }
    }
}
