//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Log_Id { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public string Log_Type { get; set; }
        public Nullable<System.DateTime> Log_Time { get; set; }
        public string Log_IP { get; set; }
        public string Log_OS { get; set; }
        public string Log_Browser { get; set; }
        public string Log_MenuName { get; set; }
        public Nullable<int> Log_MenuId { get; set; }
        public string Log_FileName { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
