//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageMenu_Point
    {
        public int MMP_Id { get; set; }
        public string MMP_FileName { get; set; }
        public bool MMP_IsUse { get; set; }
        public bool MMP_IsShow { get; set; }
        public Nullable<short> MM_Id { get; set; }
        public Nullable<short> FPI_Id { get; set; }
    }
}
