//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageMenu
    {
        public int MM_Id { get; set; }
        public string MM_Name { get; set; }
        public string MM_Type { get; set; }
        public int MM_Root { get; set; }
        public string MM_Link { get; set; }
        public string MM_Marker { get; set; }
        public int MM_Tax { get; set; }
        public int MM_PatId { get; set; }
        public string MM_Color { get; set; }
        public string MM_Font { get; set; }
        public bool MM_IsBold { get; set; }
        public bool MM_IsItalic { get; set; }
        public string MM_IcoS { get; set; }
        public string MM_IcoB { get; set; }
        public bool MM_IsUse { get; set; }
        public bool MM_IsShow { get; set; }
        public string MM_Intro { get; set; }
        public bool MM_State { get; set; }
        public string MM_Func { get; set; }
        public int MM_WinWidth { get; set; }
        public int MM_WinHeight { get; set; }
        public int MM_IcoX { get; set; }
        public int MM_IcoY { get; set; }
    }
}
