//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBoard
    {
        public int Mb_Id { get; set; }
        public string Mb_Title { get; set; }
        public bool Mb_IsTheme { get; set; }
        public string Mb_Content { get; set; }
        public string Mb_Answer { get; set; }
        public Nullable<int> Mb_PID { get; set; }
        public string Mb_UID { get; set; }
        public Nullable<int> Mb_At { get; set; }
        public Nullable<System.DateTime> Mb_CrtTime { get; set; }
        public Nullable<System.DateTime> Mb_AnsTime { get; set; }
        public bool Mb_IsAns { get; set; }
        public bool Mb_IsShow { get; set; }
        public bool Mb_IsDel { get; set; }
        public string Mb_IP { get; set; }
        public string Mb_Phone { get; set; }
        public string Mb_Email { get; set; }
        public string Mb_QQ { get; set; }
        public Nullable<int> Mb_FluxNumber { get; set; }
        public Nullable<int> Mb_ReplyNumber { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Cou_ID { get; set; }
        public string Ac_Name { get; set; }
        public string Ac_Photo { get; set; }
        public int Ac_ID { get; set; }
        public int Th_ID { get; set; }
    }
}
