//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Msg_Id { get; set; }
        public string Msg_Title { get; set; }
        public string Msg_Context { get; set; }
        public Nullable<System.DateTime> Msg_CrtTime { get; set; }
        public Nullable<System.DateTime> Msg_ToTime { get; set; }
        public Nullable<System.DateTime> Msg_ReadTime { get; set; }
        public Nullable<int> Msg_State { get; set; }
        public Nullable<int> Msg_ToId { get; set; }
        public Nullable<int> Msg_OfBox { get; set; }
        public string Msg_ToAllId { get; set; }
        public string Msg_ToAllName { get; set; }
        public Nullable<int> Msg_OwnerId { get; set; }
        public bool Msg_Del { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Org_Name { get; set; }
        public int Ac_ID { get; set; }
        public string Msg_QQ { get; set; }
        public string Msg_Phone { get; set; }
        public string Msg_ReContext { get; set; }
        public bool Msg_IsReply { get; set; }
        public int Cou_ID { get; set; }
        public Nullable<int> Ol_ID { get; set; }
        public string Msg_IP { get; set; }
        public string Ac_AccName { get; set; }
        public int Msg_PlayTime { get; set; }
        public int Msg_Likenum { get; set; }
        public string Ac_Name { get; set; }
        public string Ac_Photo { get; set; }
    }
}
