//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileUser
    {
        public int Mu_Id { get; set; }
        public string Mu_Phone { get; set; }
        public Nullable<System.DateTime> Mu_LastTime { get; set; }
        public Nullable<int> Mu_Sex { get; set; }
        public Nullable<int> Mu_Age { get; set; }
        public string Mu_Post { get; set; }
        public string Mu_Depart { get; set; }
        public Nullable<int> Mu_Number { get; set; }
        public string Mu_Version { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
