//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyAccount
    {
        public int Ma_ID { get; set; }
        public int Ac_ID { get; set; }
        public decimal Ma_Total { get; set; }
        public decimal Ma_Money { get; set; }
        public string Ma_Source { get; set; }
        public int Ma_Type { get; set; }
        public string Ma_Info { get; set; }
        public string Ma_Remark { get; set; }
        public System.DateTime Ma_CrtTime { get; set; }
        public string Rc_Code { get; set; }
        public int Org_ID { get; set; }
        public string Ma_Serial { get; set; }
        public bool Ma_IsSuccess { get; set; }
        public int Ma_From { get; set; }
        public int Pai_ID { get; set; }
        public int Ma_Status { get; set; }
        public string Ma_Buyer { get; set; }
        public string Ma_Seller { get; set; }
    }
}
