//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public int Nav_ID { get; set; }
        public int Nav_PID { get; set; }
        public string Nav_Name { get; set; }
        public string Nav_EnName { get; set; }
        public string Nav_Url { get; set; }
        public string Nav_Target { get; set; }
        public string Nav_Event { get; set; }
        public string Nav_Image { get; set; }
        public string Nav_Color { get; set; }
        public string Nav_Font { get; set; }
        public int Nav_Child { get; set; }
        public int Nav_Tax { get; set; }
        public string Nav_Intro { get; set; }
        public string Nav_Title { get; set; }
        public string Nav_Type { get; set; }
        public string Nav_Site { get; set; }
        public System.DateTime Nav_CrtTime { get; set; }
        public bool Nav_IsShow { get; set; }
        public bool Nav_IsBold { get; set; }
        public string Nav_Logo { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
