//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int Org_ID { get; set; }
        public string Org_Lang { get; set; }
        public string Org_Name { get; set; }
        public string Org_PlatformName { get; set; }
        public string Org_Keywords { get; set; }
        public string Org_Description { get; set; }
        public string Org_EnName { get; set; }
        public string Org_AbbrName { get; set; }
        public string Org_AbbrEnName { get; set; }
        public string Org_Address { get; set; }
        public string Org_Phone { get; set; }
        public string Org_Fax { get; set; }
        public string Org_Zip { get; set; }
        public string Org_WebSite { get; set; }
        public string Org_TwoDomain { get; set; }
        public string Org_Email { get; set; }
        public string Org_Weixin { get; set; }
        public string Org_Intro { get; set; }
        public string Org_CoBank { get; set; }
        public string Org_BankAcc { get; set; }
        public string Org_Owner { get; set; }
        public string Org_License { get; set; }
        public string Org_LicensePic { get; set; }
        public string Org_Longitude { get; set; }
        public string Org_Latitude { get; set; }
        public string Org_Province { get; set; }
        public string Org_City { get; set; }
        public string Org_District { get; set; }
        public string Org_Street { get; set; }
        public string Org_Logo { get; set; }
        public string Org_QrCodeUrl { get; set; }
        public System.DateTime Org_RegTime { get; set; }
        public bool Org_IsRoot { get; set; }
        public bool Org_IsUse { get; set; }
        public bool Org_IsPass { get; set; }
        public bool Org_IsDefault { get; set; }
        public int Olv_ID { get; set; }
        public string Olv_Name { get; set; }
        public string Org_Linkman { get; set; }
        public string Org_LinkmanPhone { get; set; }
        public string Org_LinkmanQQ { get; set; }
        public string Org_Template { get; set; }
        public string Org_Extracode { get; set; }
        public string Org_Config { get; set; }
        public string Org_TemplateMobi { get; set; }
        public bool Org_IsShow { get; set; }
        public string Org_ICP { get; set; }
        public string Org_QrCode { get; set; }
        public string Org_GonganBeian { get; set; }
    }
}
