//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganLevel
    {
        public int Olv_ID { get; set; }
        public int Olv_Level { get; set; }
        public string Olv_Name { get; set; }
        public string Olv_Intro { get; set; }
        public bool Olv_IsUse { get; set; }
        public string Olv_Tag { get; set; }
        public int Olv_Tax { get; set; }
        public bool Olv_IsDefault { get; set; }
        public int Ps_ID { get; set; }
    }
}
