//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outline
    {
        public int Ol_ID { get; set; }
        public string Ol_Name { get; set; }
        public string Ol_Intro { get; set; }
        public int Ol_PID { get; set; }
        public int Ol_Tax { get; set; }
        public int Ol_Level { get; set; }
        public bool Ol_IsUse { get; set; }
        public bool Ol_IsFree { get; set; }
        public string Ol_Courseware { get; set; }
        public string Ol_Video { get; set; }
        public string Ol_LessonPlan { get; set; }
        public int Cou_ID { get; set; }
        public string Ol_UID { get; set; }
        public string Ol_XPath { get; set; }
        public int Ol_QusNumber { get; set; }
        public int Org_ID { get; set; }
        public int Sbj_ID { get; set; }
        public int Ol_QuesCount { get; set; }
        public bool Ol_IsFinish { get; set; }
        public bool Ol_IsNode { get; set; }
        public bool Ol_IsVideo { get; set; }
        public bool Ol_IsLive { get; set; }
        public System.DateTime Ol_LiveTime { get; set; }
        public int Ol_LiveSpan { get; set; }
        public string Ol_LiveID { get; set; }
    }
}
