//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlineEvent
    {
        public int Oe_ID { get; set; }
        public int Ol_ID { get; set; }
        public string Ol_UID { get; set; }
        public string Oe_Title { get; set; }
        public int Oe_Width { get; set; }
        public int Oe_Height { get; set; }
        public bool Oe_IsUse { get; set; }
        public int Oe_EventType { get; set; }
        public int Oe_TriggerPoint { get; set; }
        public string Oe_Context { get; set; }
        public string Oe_Datatable { get; set; }
        public int Oe_Questype { get; set; }
        public string Oe_Answer { get; set; }
        public int Cou_ID { get; set; }
        public int Org_ID { get; set; }
        public System.DateTime Oe_CrtTime { get; set; }
    }
}
