//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayInterface
    {
        public int Pai_ID { get; set; }
        public string Pai_Name { get; set; }
        public string Pai_Pattern { get; set; }
        public int Pai_Tax { get; set; }
        public string Pai_Intro { get; set; }
        public string Pai_Currency { get; set; }
        public string Pai_Platform { get; set; }
        public string Pai_ParterID { get; set; }
        public string Pai_Key { get; set; }
        public string Pai_InterfaceType { get; set; }
        public float Pai_Feerate { get; set; }
        public string Pai_Config { get; set; }
        public bool Pai_IsEnable { get; set; }
        public int Org_ID { get; set; }
        public string Pai_Returl { get; set; }
        public string Pai_Scene { get; set; }
    }
}
