//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Pic_Id { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public string Col_Name { get; set; }
        public string Pic_Name { get; set; }
        public string Pic_Intro { get; set; }
        public string Pic_FilePath { get; set; }
        public string Pic_FilePathSmall { get; set; }
        public bool Pic_IsShow { get; set; }
        public string Pic_Keywords { get; set; }
        public string Pic_Descr { get; set; }
        public bool Pic_IsRec { get; set; }
        public bool Pic_IsTop { get; set; }
        public bool Pic_IsHot { get; set; }
        public bool Pic_IsDel { get; set; }
        public bool Pic_IsCover { get; set; }
        public Nullable<System.DateTime> Pic_CrtTime { get; set; }
        public Nullable<int> Pic_Size { get; set; }
        public Nullable<int> Pic_Width { get; set; }
        public Nullable<int> Pic_Height { get; set; }
        public Nullable<int> Pic_Number { get; set; }
        public Nullable<int> Pic_Tax { get; set; }
        public string Pic_Uid { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public bool Pic_IsStatic { get; set; }
        public Nullable<System.DateTime> Pic_PushTime { get; set; }
        public string Pic_Label { get; set; }
        public string Pic_Type { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
