//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictMiniature
    {
        public int Pmin_Id { get; set; }
        public Nullable<int> Pmin_Tax { get; set; }
        public Nullable<int> Pmin_Width { get; set; }
        public Nullable<int> Pmin_Height { get; set; }
        public string Pmin_Unit { get; set; }
        public bool Pmin_IsRestrain { get; set; }
        public string Pmin_RestrainObj { get; set; }
        public bool Pmin_IsUse { get; set; }
        public string Pmin_File { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
