//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointAccount
    {
        public int Pa_ID { get; set; }
        public int Ac_ID { get; set; }
        public int Pa_Total { get; set; }
        public int Pa_TotalAmount { get; set; }
        public int Pa_Value { get; set; }
        public string Pa_Source { get; set; }
        public int Pa_Type { get; set; }
        public string Pa_Info { get; set; }
        public string Pa_Remark { get; set; }
        public System.DateTime Pa_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Pa_Serial { get; set; }
        public int Pa_From { get; set; }
    }
}
