//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFactory
    {
        public int Pfact_Id { get; set; }
        public string Pfact_Name { get; set; }
        public string Pfact_Addr { get; set; }
        public string Pfact_Zip { get; set; }
        public string Pfact_Intro { get; set; }
        public string Pfact_Tel { get; set; }
        public string Pfact_Website { get; set; }
        public bool Pfact_IsUse { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
