//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Pd_Id { get; set; }
        public string Pd_Name { get; set; }
        public Nullable<int> Pd_Tax { get; set; }
        public bool Pd_IsUse { get; set; }
        public bool Pd_IsNew { get; set; }
        public bool Pd_IsRec { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public string Col_Name { get; set; }
        public string Pd_Model { get; set; }
        public string Pd_Code { get; set; }
        public Nullable<float> Pd_Prise { get; set; }
        public Nullable<float> Pd_Weight { get; set; }
        public string Pd_ColorName { get; set; }
        public string Pd_Color { get; set; }
        public string Pd_KeyWords { get; set; }
        public string Pd_Descr { get; set; }
        public string Pd_Logo { get; set; }
        public string Pd_LogoSmall { get; set; }
        public string Pd_QrCode { get; set; }
        public Nullable<int> Pd_Number { get; set; }
        public Nullable<int> Pd_Stocks { get; set; }
        public string Pd_Unit { get; set; }
        public Nullable<System.DateTime> Pd_SaleTime { get; set; }
        public Nullable<System.DateTime> Pd_CrtTime { get; set; }
        public bool Pd_IsNote { get; set; }
        public string Pd_Intro { get; set; }
        public string Pd_Details { get; set; }
        public bool Pd_IsDel { get; set; }
        public bool Pd_IsStatic { get; set; }
        public Nullable<System.DateTime> Pd_PushTime { get; set; }
        public string Pd_Label { get; set; }
        public string Pd_Uid { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<int> Pfact_Id { get; set; }
        public Nullable<int> Pori_Id { get; set; }
        public Nullable<int> Pmat_Id { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
