//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitSharing
    {
        public int Ps_ID { get; set; }
        public bool Ps_IsTheme { get; set; }
        public bool Ps_IsUse { get; set; }
        public int Ps_Level { get; set; }
        public string Ps_Intro { get; set; }
        public int Ps_Moneyratio { get; set; }
        public int Ps_Couponratio { get; set; }
        public decimal Ps_MoneyValue { get; set; }
        public int Ps_CouponValue { get; set; }
        public int Ps_PID { get; set; }
        public string Ps_Name { get; set; }
    }
}
