//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purview
    {
        public int Pur_Id { get; set; }
        public Nullable<int> Dep_Id { get; set; }
        public Nullable<int> EGrp_Id { get; set; }
        public Nullable<int> Posi_Id { get; set; }
        public Nullable<int> MM_Id { get; set; }
        public string Pur_State { get; set; }
        public string Pur_Type { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Olv_ID { get; set; }
    }
}
