//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuesAnswer
    {
        public int Ans_ID { get; set; }
        public int Qus_ID { get; set; }
        public string Qus_UID { get; set; }
        public string Ans_Context { get; set; }
        public bool Ans_IsCorrect { get; set; }
    }
}
