//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeSet
    {
        public int Rs_ID { get; set; }
        public int Rs_Count { get; set; }
        public int Rs_Price { get; set; }
        public System.DateTime Rs_CrtTime { get; set; }
        public string Rs_Theme { get; set; }
        public string Rs_Intro { get; set; }
        public string Rs_Pw { get; set; }
        public int Rs_UsedCount { get; set; }
        public int Org_ID { get; set; }
        public System.DateTime Rs_LimitStart { get; set; }
        public System.DateTime Rs_LimitEnd { get; set; }
        public bool Rs_IsEnable { get; set; }
        public int Rs_CodeLength { get; set; }
        public int Rs_PwLength { get; set; }
    }
}
