//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeCode
    {
        public int Rc_ID { get; set; }
        public string Rc_Code { get; set; }
        public string Rc_Pw { get; set; }
        public int Rc_Price { get; set; }
        public System.DateTime Rc_CrtTime { get; set; }
        public System.DateTime Rc_UsedTime { get; set; }
        public Nullable<bool> Rc_IsEnable { get; set; }
        public bool Rc_IsUsed { get; set; }
        public int Rc_Type { get; set; }
        public int Rs_ID { get; set; }
        public int Org_ID { get; set; }
        public int Ac_ID { get; set; }
        public string Ac_AccName { get; set; }
        public System.DateTime Rc_LimitStart { get; set; }
        public System.DateTime Rc_LimitEnd { get; set; }
        public string Rc_QrcodeBase64 { get; set; }
    }
}
