//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowPicture
    {
        public int Shp_ID { get; set; }
        public string Shp_File { get; set; }
        public string Shp_Url { get; set; }
        public string Shp_Target { get; set; }
        public bool Shp_IsShow { get; set; }
        public string Shp_Site { get; set; }
        public string Shp_BgColor { get; set; }
        public int Shp_Tax { get; set; }
        public string Shp_Intro { get; set; }
        public int Org_ID { get; set; }
    }
}
