//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleSignOn
    {
        public int SSO_ID { get; set; }
        public string SSO_Name { get; set; }
        public Nullable<bool> SSO_IsUse { get; set; }
        public string SSO_APPID { get; set; }
        public bool SSO_IsAdd { get; set; }
        public string SSO_Domain { get; set; }
        public string SSO_Direction { get; set; }
        public string SSO_Phone { get; set; }
        public string SSO_Email { get; set; }
        public string SSO_Info { get; set; }
        public System.DateTime SSO_CrtTime { get; set; }
        public string SSO_Power { get; set; }
        public string SSO_Config { get; set; }
    }
}
