//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsFault
    {
        public int Smf_Id { get; set; }
        public string Smf_Context { get; set; }
        public Nullable<System.DateTime> Smf_SendTime { get; set; }
        public Nullable<System.DateTime> Smf_CrtTime { get; set; }
        public string Smf_MobileTel { get; set; }
        public string Smf_SendName { get; set; }
        public string Smf_Company { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
