//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsMessage
    {
        public int SMS_Id { get; set; }
        public string Sms_Context { get; set; }
        public Nullable<System.DateTime> Sms_SendTime { get; set; }
        public Nullable<System.DateTime> Sms_CrtTime { get; set; }
        public Nullable<int> Sms_Type { get; set; }
        public Nullable<int> Sms_SendId { get; set; }
        public string Sms_SendName { get; set; }
        public Nullable<int> Sms_MailBox { get; set; }
        public Nullable<int> Sms_State { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
