//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int Sp_Id { get; set; }
        public Nullable<int> Sp_PatId { get; set; }
        public Nullable<int> Sp_Tax { get; set; }
        public string Sp_Name { get; set; }
        public bool Sp_IsUse { get; set; }
        public bool Sp_IsShow { get; set; }
        public bool Sp_IsOut { get; set; }
        public string Sp_OutUrl { get; set; }
        public string Sp_Intro { get; set; }
        public string Sp_Details { get; set; }
        public string Sp_Keywords { get; set; }
        public string Sp_Descr { get; set; }
        public Nullable<System.DateTime> Sp_PushTime { get; set; }
        public string Sp_Label { get; set; }
        public string Sp_Tootip { get; set; }
        public string Sp_Banner { get; set; }
        public string Sp_Uid { get; set; }
        public string Sp_Logo { get; set; }
        public string Sp_QrCode { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
