//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Notes
    {
        public int Stn_ID { get; set; }
        public Nullable<int> Stn_PID { get; set; }
        public int Ac_ID { get; set; }
        public int Cou_ID { get; set; }
        public int Qus_ID { get; set; }
        public int Qus_Type { get; set; }
        public string Qus_Title { get; set; }
        public string Stn_Title { get; set; }
        public string Stn_Context { get; set; }
        public System.DateTime Stn_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
