//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int St_ID { get; set; }
        public string St_AccName { get; set; }
        public string St_Pw { get; set; }
        public string St_Qus { get; set; }
        public string St_Anwser { get; set; }
        public string St_Name { get; set; }
        public string St_Pinyin { get; set; }
        public int St_Age { get; set; }
        public System.DateTime St_Birthday { get; set; }
        public string St_IDCardNumber { get; set; }
        public string St_Photo { get; set; }
        public string St_Signature { get; set; }
        public string St_Intro { get; set; }
        public string St_Major { get; set; }
        public string St_Education { get; set; }
        public int St_Sex { get; set; }
        public string St_Native { get; set; }
        public string St_Nation { get; set; }
        public string St_CodeNumber { get; set; }
        public string St_Address { get; set; }
        public string St_AddrContact { get; set; }
        public string St_Phone { get; set; }
        public bool St_IsOpenPhone { get; set; }
        public string St_PhoneMobi { get; set; }
        public bool St_IsOpenMobi { get; set; }
        public string St_Email { get; set; }
        public string St_Qq { get; set; }
        public string St_Weixin { get; set; }
        public string St_Zip { get; set; }
        public string St_LinkMan { get; set; }
        public string St_LinkManPhone { get; set; }
        public bool St_IsPass { get; set; }
        public bool St_IsUse { get; set; }
        public System.DateTime St_RegTime { get; set; }
        public System.DateTime St_LastTime { get; set; }
        public System.DateTime St_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Sts_ID { get; set; }
        public string Sts_Name { get; set; }
        public float St_Money { get; set; }
        public string St_LastIP { get; set; }
        public string Dep_CnName { get; set; }
        public int Dep_Id { get; set; }
        public string St_CheckUID { get; set; }
        public int St_CurrCourse { get; set; }
        public int Ac_ID { get; set; }
        public string Ac_UID { get; set; }
    }
}
