//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Ques
    {
        public int Squs_ID { get; set; }
        public int Ac_ID { get; set; }
        public int Cou_ID { get; set; }
        public int Qus_ID { get; set; }
        public int Qus_Type { get; set; }
        public int Qus_Diff { get; set; }
        public int Sbj_ID { get; set; }
        public int Squs_Level { get; set; }
        public System.DateTime Squs_CrtTime { get; set; }
    }
}
