//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSort
    {
        public int Sts_ID { get; set; }
        public string Sts_Name { get; set; }
        public int Sts_Tax { get; set; }
        public string Sts_Intro { get; set; }
        public bool Sts_IsUse { get; set; }
        public bool Sts_IsDefault { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public string Dep_CnName { get; set; }
        public int Dep_Id { get; set; }
    }
}
