//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public string Sbj_ByName { get; set; }
        public string Sbj_Intro { get; set; }
        public int Sbj_Tax { get; set; }
        public bool Sbj_IsUse { get; set; }
        public System.DateTime Sbj_CrtTime { get; set; }
        public int Sbj_PassScore { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Sbj_PID { get; set; }
        public int Sbj_Level { get; set; }
        public string Sbj_XPath { get; set; }
        public int Sbj_CouNumber { get; set; }
        public string Sbj_Logo { get; set; }
        public string Sbj_LogoSmall { get; set; }
        public int Dep_Id { get; set; }
        public string Dep_CnName { get; set; }
        public bool Sbj_IsRec { get; set; }
        public string Sbj_Details { get; set; }
    }
}
