//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPara
    {
        public int Sys_Id { get; set; }
        public string Sys_Key { get; set; }
        public string Sys_Value { get; set; }
        public string Sys_Default { get; set; }
        public string Sys_ParaIntro { get; set; }
        public string Sys_Unit { get; set; }
        public string Sys_SelectUnit { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Org_Name { get; set; }
    }
}
