//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Task_Id { get; set; }
        public string Task_Name { get; set; }
        public string Task_Context { get; set; }
        public Nullable<System.DateTime> Task_CrtTime { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<System.DateTime> Task_StartTime { get; set; }
        public Nullable<System.DateTime> Task_EndTime { get; set; }
        public string Task_State { get; set; }
        public bool Task_IsComplete { get; set; }
        public Nullable<System.DateTime> Task_CompleteTime { get; set; }
        public Nullable<int> Task_Level { get; set; }
        public Nullable<int> Task_Tax { get; set; }
        public Nullable<int> Task_WorkerId { get; set; }
        public string Task_WorkerName { get; set; }
        public bool Task_IsUse { get; set; }
        public string Task_WorkLog { get; set; }
        public Nullable<int> Task_CompletePer { get; set; }
        public bool Task_IsGoback { get; set; }
        public string Task_GobackText { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
