//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherHistory
    {
        public int Thh_ID { get; set; }
        public string Thh_Theme { get; set; }
        public System.DateTime Thh_StartTime { get; set; }
        public Nullable<System.DateTime> Thh_EndTime { get; set; }
        public Nullable<System.DateTime> Thh_CrtTime { get; set; }
        public string Thh_Type { get; set; }
        public string Thh_Intro { get; set; }
        public string Thh_Success { get; set; }
        public string Thh_School { get; set; }
        public string Thh_Major { get; set; }
        public string Thh_Education { get; set; }
        public string Thh_Compay { get; set; }
        public string Thh_Job { get; set; }
        public string Thh_Post { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
    }
}
