//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSort
    {
        public int Ths_ID { get; set; }
        public string Ths_Name { get; set; }
        public int Ths_Tax { get; set; }
        public string Ths_Intro { get; set; }
        public bool Ths_IsUse { get; set; }
        public bool Ths_IsDefault { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
