//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Th_ID { get; set; }
        public string Th_AccName { get; set; }
        public string Th_Pw { get; set; }
        public string Th_Qus { get; set; }
        public string Th_Anwser { get; set; }
        public string Th_Name { get; set; }
        public string Th_Title { get; set; }
        public string Th_Pinyin { get; set; }
        public Nullable<int> Th_Age { get; set; }
        public Nullable<System.DateTime> Th_Birthday { get; set; }
        public string Th_IDCardNumber { get; set; }
        public string Th_Photo { get; set; }
        public string Th_Signature { get; set; }
        public string Th_Intro { get; set; }
        public string Th_Job { get; set; }
        public string Th_Major { get; set; }
        public string Th_Education { get; set; }
        public Nullable<int> Th_Sex { get; set; }
        public string Th_Native { get; set; }
        public string Th_Nation { get; set; }
        public string Th_CodeNumber { get; set; }
        public string Th_Address { get; set; }
        public string Th_AddrContact { get; set; }
        public string Th_Phone { get; set; }
        public Nullable<bool> Th_IsOpenPhone { get; set; }
        public string Th_PhoneMobi { get; set; }
        public Nullable<bool> Th_IsOpenMobi { get; set; }
        public string Th_Email { get; set; }
        public string Th_Qq { get; set; }
        public string Th_Weixin { get; set; }
        public string Th_Zip { get; set; }
        public string Th_LinkMan { get; set; }
        public string Th_LinkManPhone { get; set; }
        public Nullable<bool> Th_IsPass { get; set; }
        public Nullable<bool> Th_IsUse { get; set; }
        public Nullable<System.DateTime> Th_RegTime { get; set; }
        public Nullable<System.DateTime> Th_LastTime { get; set; }
        public Nullable<System.DateTime> Th_CrtTime { get; set; }
        public Nullable<int> Th_Tax { get; set; }
        public Nullable<int> Th_Score { get; set; }
        public Nullable<int> Th_ViewNum { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public string Org_Name { get; set; }
        public Nullable<int> Ths_ID { get; set; }
        public string Ths_Name { get; set; }
        public Nullable<int> Dep_Id { get; set; }
        public Nullable<bool> Th_IsShow { get; set; }
        public Nullable<int> Ac_ID { get; set; }
        public string Ac_UID { get; set; }
    }
}
