//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherComment
    {
        public int Thc_ID { get; set; }
        public int Ac_ID { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
        public double Thc_Score { get; set; }
        public string Thc_Comment { get; set; }
        public string Thc_Reply { get; set; }
        public System.DateTime Thc_CrtTime { get; set; }
        public string Thc_Device { get; set; }
        public string Thc_IP { get; set; }
        public bool Thc_IsUse { get; set; }
        public bool Thc_IsShow { get; set; }
        public int Org_ID { get; set; }
    }
}
