//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Team_ID { get; set; }
        public Nullable<int> Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public string Team_Name { get; set; }
        public string Team_ByName { get; set; }
        public string Team_Intro { get; set; }
        public Nullable<int> Team_Tax { get; set; }
        public bool Team_IsUse { get; set; }
        public Nullable<int> Team_Count { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<System.DateTime> Team_CrtTime { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
