//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int Tr_ID { get; set; }
        public Nullable<float> Tr_Score { get; set; }
        public Nullable<float> Tr_ScoreFinal { get; set; }
        public Nullable<float> Tr_Draw { get; set; }
        public Nullable<float> Tr_Colligate { get; set; }
        public string Tr_Results { get; set; }
        public Nullable<System.DateTime> Tr_CrtTime { get; set; }
        public string Tr_IP { get; set; }
        public string Tr_Name { get; set; }
        public string Tr_Mac { get; set; }
        public bool Tr_IsSubmit { get; set; }
        public string Tr_UID { get; set; }
        public Nullable<int> Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public Nullable<int> Tp_Id { get; set; }
        public string Tp_Name { get; set; }
        public int Ac_ID { get; set; }
        public string Ac_Name { get; set; }
        public int Sts_ID { get; set; }
        public string Sts_Name { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int St_Sex { get; set; }
        public string St_IDCardNumber { get; set; }
        public int Cou_ID { get; set; }
    }
}
