//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Test_ID { get; set; }
        public string Test_Name { get; set; }
        public Nullable<System.DateTime> Test_StartTime { get; set; }
        public Nullable<int> Test_Span { get; set; }
        public string Test_Tearcher { get; set; }
        public string Test_Room { get; set; }
        public Nullable<int> Tp_Id { get; set; }
        public string Tp_Name { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
    }
}
