//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public int Tp_Id { get; set; }
        public string Tp_Name { get; set; }
        public int Tp_Type { get; set; }
        public string Tp_Intro { get; set; }
        public string Tp_Logo { get; set; }
        public string Tp_Author { get; set; }
        public int Tp_Total { get; set; }
        public int Tp_Count { get; set; }
        public System.DateTime Tp_CrtTime { get; set; }
        public System.DateTime Tp_Lasttime { get; set; }
        public int Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public int Tp_Diff { get; set; }
        public bool Tp_IsRec { get; set; }
        public bool Tp_IsBuild { get; set; }
        public bool Tp_IsUse { get; set; }
        public int Tp_Span { get; set; }
        public string Tp_UID { get; set; }
        public int Tp_Diff2 { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Th_ID { get; set; }
        public string Th_Name { get; set; }
        public int Tp_PassScore { get; set; }
        public int Cou_ID { get; set; }
        public string Tp_Remind { get; set; }
        public string Tp_SubName { get; set; }
        public int Tp_FromType { get; set; }
        public string Tp_FromConfig { get; set; }
        public string Cou_Name { get; set; }
    }
}
