//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaperQues
    {
        public int Tq_Id { get; set; }
        public Nullable<int> Qk_Id { get; set; }
        public Nullable<int> Tp_Id { get; set; }
        public Nullable<float> Tq_Number { get; set; }
        public Nullable<int> Tq_Percent { get; set; }
        public Nullable<int> Tq_Type { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
