//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaperItem
    {
        public int TPI_ID { get; set; }
        public string Tp_UID { get; set; }
        public int TPI_Type { get; set; }
        public int TPI_Percent { get; set; }
        public int TPI_Number { get; set; }
        public int TPI_Count { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
        public int Ol_ID { get; set; }
    }
}
