//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrPlan
    {
        public int TrP_Id { get; set; }
        public System.DateTime TrP_Time { get; set; }
        public System.DateTime TrP_Start { get; set; }
        public System.DateTime TrP_End { get; set; }
        public int Dep_Id { get; set; }
        public string Dep_CnName { get; set; }
        public int Sbj_ID { get; set; }
        public string Sbj_Name { get; set; }
        public int TrP_GroupType { get; set; }
        public int TrP_Num { get; set; }
        public string TrP_Content { get; set; }
        public string TrP_Location { get; set; }
        public string TrP_Teacher { get; set; }
        public string TrP_Way { get; set; }
        public int TrP_Result { get; set; }
        public string TrP_UID { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
