//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_Id { get; set; }
        public string User_AccName { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> User_Sex { get; set; }
        public bool User_IsUse { get; set; }
        public string User_Pw { get; set; }
        public string User_Email { get; set; }
        public string User_Qus { get; set; }
        public string User_Ans { get; set; }
        public Nullable<System.DateTime> User_RegTime { get; set; }
        public Nullable<System.DateTime> User_LastTime { get; set; }
        public Nullable<int> User_LoginNumber { get; set; }
        public string User_Tel { get; set; }
        public string User_MobileTel { get; set; }
        public string User_QQ { get; set; }
        public string User_Msn { get; set; }
        public Nullable<int> UGrp_Id { get; set; }
        public string UGrp_Name { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Org_Name { get; set; }
    }
}
