//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Vi_Id { get; set; }
        public string Vi_Name { get; set; }
        public string Vi_Intro { get; set; }
        public string Vi_Details { get; set; }
        public string Vi_VideoFile { get; set; }
        public string Vi_FilePath { get; set; }
        public string Vi_FilePathSmall { get; set; }
        public bool Vi_IsShow { get; set; }
        public string Vi_Keywords { get; set; }
        public string Vi_Descr { get; set; }
        public bool Vi_IsRec { get; set; }
        public bool Vi_IsTop { get; set; }
        public bool Vi_IsHot { get; set; }
        public bool Vi_IsDel { get; set; }
        public bool Vi_IsCover { get; set; }
        public Nullable<System.DateTime> Vi_CrtTime { get; set; }
        public Nullable<int> Vi_Size { get; set; }
        public Nullable<int> Vi_Width { get; set; }
        public Nullable<int> Vi_Height { get; set; }
        public Nullable<int> Vi_Number { get; set; }
        public Nullable<int> Vi_Tax { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public string Col_Name { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public bool Vi_IsStatic { get; set; }
        public Nullable<System.DateTime> Vi_PushTime { get; set; }
        public string Vi_Label { get; set; }
        public string Vi_Uid { get; set; }
        public string OtherData { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
