//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Vt_Id { get; set; }
        public string Vt_UniqueId { get; set; }
        public bool Vt_IsTheme { get; set; }
        public string Vt_Name { get; set; }
        public Nullable<int> Vt_Type { get; set; }
        public string Vt_Intro { get; set; }
        public Nullable<int> Vt_Tax { get; set; }
        public Nullable<int> Vt_SelectType { get; set; }
        public bool Vt_IsShow { get; set; }
        public bool Vt_IsUse { get; set; }
        public bool Vt_IsAllowSee { get; set; }
        public bool Vt_IsImage { get; set; }
        public Nullable<System.DateTime> Vt_CrtTime { get; set; }
        public Nullable<System.DateTime> Vt_StartTime { get; set; }
        public Nullable<System.DateTime> Vt_OverTime { get; set; }
        public string Vt_Logo { get; set; }
        public string Vt_Image { get; set; }
        public string Vt_ImageSmall { get; set; }
        public Nullable<int> Vt_Number { get; set; }
        public int Org_ID { get; set; }
        public string Org_Name { get; set; }
    }
}
