//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingTalkUser
    {
        public string ID { get; set; }
        public string name { get; set; }
        public string userid { get; set; }
        public string unionid { get; set; }
        public string mobile { get; set; }
        public string department { get; set; }
        public System.DateTime Editdate { get; set; }
        public System.DateTime Inputdate { get; set; }
    }
}
