//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyUser_Yuyue
    {
        public int id { get; set; }
        public string userID { get; set; }
        public string userName { get; set; }
        public string mobile { get; set; }
        public string department { get; set; }
        public string avatar { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> templatesID { get; set; }
        public string topUserID { get; set; }
        public string dingdingUserid { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<int> isDel { get; set; }
        public string unionid { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
