//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string YourPop { get; set; }
        public string YourName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string OperPop { get; set; }
        public Nullable<int> classID { get; set; }
        public string UsingSickID { get; set; }
        public Nullable<decimal> KeFuPercent { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<int> BirthM { get; set; }
        public Nullable<int> BirthD { get; set; }
        public Nullable<int> jiaose { get; set; }
        public string DelState { get; set; }
    }
}
